//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FormBuilderModel", "FK_form_field_values_form_fields", "form_fields", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FormBuilder.FormField), "form_field_values", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FormBuilder.FormFieldValue), true)]
[assembly: EdmRelationshipAttribute("FormBuilderModel", "form_form_fields", "form_fields", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FormBuilder.FormField), "form", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FormBuilder.Form))]

#endregion

namespace FormBuilder
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FormBuilderEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FormBuilderEntities object using the connection string found in the 'FormBuilderEntities' section of the application configuration file.
        /// </summary>
        public FormBuilderEntities() : base("name=FormBuilderEntities", "FormBuilderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FormBuilderEntities object.
        /// </summary>
        public FormBuilderEntities(string connectionString) : base(connectionString, "FormBuilderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FormBuilderEntities object.
        /// </summary>
        public FormBuilderEntities(EntityConnection connection) : base(connection, "FormBuilderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Form> Forms
        {
            get
            {
                if ((_Forms == null))
                {
                    _Forms = base.CreateObjectSet<Form>("Forms");
                }
                return _Forms;
            }
        }
        private ObjectSet<Form> _Forms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FormFieldValue> FormFieldValues
        {
            get
            {
                if ((_FormFieldValues == null))
                {
                    _FormFieldValues = base.CreateObjectSet<FormFieldValue>("FormFieldValues");
                }
                return _FormFieldValues;
            }
        }
        private ObjectSet<FormFieldValue> _FormFieldValues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FormField> FormFields
        {
            get
            {
                if ((_FormFields == null))
                {
                    _FormFields = base.CreateObjectSet<FormField>("FormFields");
                }
                return _FormFields;
            }
        }
        private ObjectSet<FormField> _FormFields;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Forms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToForms(Form form)
        {
            base.AddObject("Forms", form);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FormFieldValues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormFieldValues(FormFieldValue formFieldValue)
        {
            base.AddObject("FormFieldValues", formFieldValue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FormFields EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormFields(FormField formField)
        {
            base.AddObject("FormFields", formField);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FormBuilderModel", Name="Form")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Form : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Form object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="slug">Initial value of the Slug property.</param>
        /// <param name="confirmationMessage">Initial value of the ConfirmationMessage property.</param>
        public static Form CreateForm(global::System.Int32 id, global::System.String title, global::System.String slug, global::System.String confirmationMessage)
        {
            Form form = new Form();
            form.ID = id;
            form.Title = title;
            form.Slug = slug;
            form.ConfirmationMessage = confirmationMessage;
            return form;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Slug
        {
            get
            {
                return _Slug;
            }
            set
            {
                OnSlugChanging(value);
                ReportPropertyChanging("Slug");
                _Slug = StructuralObject.SetValidValue(value, false, "Slug");
                ReportPropertyChanged("Slug");
                OnSlugChanged();
            }
        }
        private global::System.String _Slug;
        partial void OnSlugChanging(global::System.String value);
        partial void OnSlugChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConfirmationMessage
        {
            get
            {
                return _ConfirmationMessage;
            }
            set
            {
                OnConfirmationMessageChanging(value);
                ReportPropertyChanging("ConfirmationMessage");
                _ConfirmationMessage = StructuralObject.SetValidValue(value, false, "ConfirmationMessage");
                ReportPropertyChanged("ConfirmationMessage");
                OnConfirmationMessageChanged();
            }
        }
        private global::System.String _ConfirmationMessage;
        partial void OnConfirmationMessageChanging(global::System.String value);
        partial void OnConfirmationMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value, "DateAdded");
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateAdded;
        partial void OnDateAddedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateAddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Theme
        {
            get
            {
                return _Theme;
            }
            set
            {
                OnThemeChanging(value);
                ReportPropertyChanging("Theme");
                _Theme = StructuralObject.SetValidValue(value, true, "Theme");
                ReportPropertyChanged("Theme");
                OnThemeChanged();
            }
        }
        private global::System.String _Theme;
        partial void OnThemeChanging(global::System.String value);
        partial void OnThemeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NotificationEmail
        {
            get
            {
                return _NotificationEmail;
            }
            set
            {
                OnNotificationEmailChanging(value);
                ReportPropertyChanging("NotificationEmail");
                _NotificationEmail = StructuralObject.SetValidValue(value, true, "NotificationEmail");
                ReportPropertyChanged("NotificationEmail");
                OnNotificationEmailChanged();
            }
        }
        private global::System.String _NotificationEmail;
        partial void OnNotificationEmailChanging(global::System.String value);
        partial void OnNotificationEmailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FormBuilderModel", "form_form_fields", "form_fields")]
        public EntityCollection<FormField> FormFields
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FormField>("FormBuilderModel.form_form_fields", "form_fields");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FormField>("FormBuilderModel.form_form_fields", "form_fields", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FormBuilderModel", Name="FormField")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormField : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FormField object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="selectedOption">Initial value of the SelectedOption property.</param>
        /// <param name="dateAdded">Initial value of the DateAdded property.</param>
        public static FormField CreateFormField(global::System.Int32 id, global::System.String selectedOption, global::System.DateTime dateAdded)
        {
            FormField formField = new FormField();
            formField.ID = id;
            formField.SelectedOption = selectedOption;
            formField.DateAdded = dateAdded;
            return formField;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, true, "Label");
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true, "Text");
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FieldType
        {
            get
            {
                return _FieldType;
            }
            set
            {
                OnFieldTypeChanging(value);
                ReportPropertyChanging("FieldType");
                _FieldType = StructuralObject.SetValidValue(value, true, "FieldType");
                ReportPropertyChanged("FieldType");
                OnFieldTypeChanged();
            }
        }
        private global::System.String _FieldType;
        partial void OnFieldTypeChanging(global::System.String value);
        partial void OnFieldTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRequired
        {
            get
            {
                return _IsRequired;
            }
            set
            {
                OnIsRequiredChanging(value);
                ReportPropertyChanging("IsRequired");
                _IsRequired = StructuralObject.SetValidValue(value, "IsRequired");
                ReportPropertyChanged("IsRequired");
                OnIsRequiredChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRequired;
        partial void OnIsRequiredChanging(Nullable<global::System.Boolean> value);
        partial void OnIsRequiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxChars
        {
            get
            {
                return _MaxChars;
            }
            set
            {
                OnMaxCharsChanging(value);
                ReportPropertyChanging("MaxChars");
                _MaxChars = StructuralObject.SetValidValue(value, "MaxChars");
                ReportPropertyChanged("MaxChars");
                OnMaxCharsChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxChars;
        partial void OnMaxCharsChanging(Nullable<global::System.Int32> value);
        partial void OnMaxCharsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoverText
        {
            get
            {
                return _HoverText;
            }
            set
            {
                OnHoverTextChanging(value);
                ReportPropertyChanging("HoverText");
                _HoverText = StructuralObject.SetValidValue(value, true, "HoverText");
                ReportPropertyChanged("HoverText");
                OnHoverTextChanged();
            }
        }
        private global::System.String _HoverText;
        partial void OnHoverTextChanging(global::System.String value);
        partial void OnHoverTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hint
        {
            get
            {
                return _Hint;
            }
            set
            {
                OnHintChanging(value);
                ReportPropertyChanging("Hint");
                _Hint = StructuralObject.SetValidValue(value, true, "Hint");
                ReportPropertyChanged("Hint");
                OnHintChanged();
            }
        }
        private global::System.String _Hint;
        partial void OnHintChanging(global::System.String value);
        partial void OnHintChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubLabel
        {
            get
            {
                return _SubLabel;
            }
            set
            {
                OnSubLabelChanging(value);
                ReportPropertyChanging("SubLabel");
                _SubLabel = StructuralObject.SetValidValue(value, true, "SubLabel");
                ReportPropertyChanged("SubLabel");
                OnSubLabelChanged();
            }
        }
        private global::System.String _SubLabel;
        partial void OnSubLabelChanging(global::System.String value);
        partial void OnSubLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value, true, "Size");
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.String _Size;
        partial void OnSizeChanging(global::System.String value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SelectedOption
        {
            get
            {
                return _SelectedOption;
            }
            set
            {
                OnSelectedOptionChanging(value);
                ReportPropertyChanging("SelectedOption");
                _SelectedOption = StructuralObject.SetValidValue(value, false, "SelectedOption");
                ReportPropertyChanged("SelectedOption");
                OnSelectedOptionChanged();
            }
        }
        private global::System.String _SelectedOption;
        partial void OnSelectedOptionChanging(global::System.String value);
        partial void OnSelectedOptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Columns
        {
            get
            {
                return _Columns;
            }
            set
            {
                OnColumnsChanging(value);
                ReportPropertyChanging("Columns");
                _Columns = StructuralObject.SetValidValue(value, "Columns");
                ReportPropertyChanged("Columns");
                OnColumnsChanged();
            }
        }
        private Nullable<global::System.Int32> _Columns;
        partial void OnColumnsChanging(Nullable<global::System.Int32> value);
        partial void OnColumnsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Rows
        {
            get
            {
                return _Rows;
            }
            set
            {
                OnRowsChanging(value);
                ReportPropertyChanging("Rows");
                _Rows = StructuralObject.SetValidValue(value, "Rows");
                ReportPropertyChanged("Rows");
                OnRowsChanged();
            }
        }
        private Nullable<global::System.Int32> _Rows;
        partial void OnRowsChanging(Nullable<global::System.Int32> value);
        partial void OnRowsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Options
        {
            get
            {
                return _Options;
            }
            set
            {
                OnOptionsChanging(value);
                ReportPropertyChanging("Options");
                _Options = StructuralObject.SetValidValue(value, true, "Options");
                ReportPropertyChanged("Options");
                OnOptionsChanged();
            }
        }
        private global::System.String _Options;
        partial void OnOptionsChanging(global::System.String value);
        partial void OnOptionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Validation
        {
            get
            {
                return _Validation;
            }
            set
            {
                OnValidationChanging(value);
                ReportPropertyChanging("Validation");
                _Validation = StructuralObject.SetValidValue(value, true, "Validation");
                ReportPropertyChanged("Validation");
                OnValidationChanged();
            }
        }
        private global::System.String _Validation;
        partial void OnValidationChanging(global::System.String value);
        partial void OnValidationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DomId
        {
            get
            {
                return _DomId;
            }
            set
            {
                OnDomIdChanging(value);
                ReportPropertyChanging("DomId");
                _DomId = StructuralObject.SetValidValue(value, "DomId");
                ReportPropertyChanged("DomId");
                OnDomIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DomId;
        partial void OnDomIdChanging(Nullable<global::System.Int32> value);
        partial void OnDomIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value, "Order");
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MinimumAge
        {
            get
            {
                return _MinimumAge;
            }
            set
            {
                OnMinimumAgeChanging(value);
                ReportPropertyChanging("MinimumAge");
                _MinimumAge = StructuralObject.SetValidValue(value, "MinimumAge");
                ReportPropertyChanged("MinimumAge");
                OnMinimumAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _MinimumAge;
        partial void OnMinimumAgeChanging(Nullable<global::System.Int32> value);
        partial void OnMinimumAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaximumAge
        {
            get
            {
                return _MaximumAge;
            }
            set
            {
                OnMaximumAgeChanging(value);
                ReportPropertyChanging("MaximumAge");
                _MaximumAge = StructuralObject.SetValidValue(value, "MaximumAge");
                ReportPropertyChanged("MaximumAge");
                OnMaximumAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _MaximumAge;
        partial void OnMaximumAgeChanging(Nullable<global::System.Int32> value);
        partial void OnMaximumAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HelpText
        {
            get
            {
                return _HelpText;
            }
            set
            {
                OnHelpTextChanging(value);
                ReportPropertyChanging("HelpText");
                _HelpText = StructuralObject.SetValidValue(value, true, "HelpText");
                ReportPropertyChanged("HelpText");
                OnHelpTextChanged();
            }
        }
        private global::System.String _HelpText;
        partial void OnHelpTextChanging(global::System.String value);
        partial void OnHelpTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value, "DateAdded");
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxFilesizeInKb
        {
            get
            {
                return _MaxFilesizeInKb;
            }
            set
            {
                OnMaxFilesizeInKbChanging(value);
                ReportPropertyChanging("MaxFilesizeInKb");
                _MaxFilesizeInKb = StructuralObject.SetValidValue(value, "MaxFilesizeInKb");
                ReportPropertyChanged("MaxFilesizeInKb");
                OnMaxFilesizeInKbChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxFilesizeInKb;
        partial void OnMaxFilesizeInKbChanging(Nullable<global::System.Int32> value);
        partial void OnMaxFilesizeInKbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidFileExtensions
        {
            get
            {
                return _ValidFileExtensions;
            }
            set
            {
                OnValidFileExtensionsChanging(value);
                ReportPropertyChanging("ValidFileExtensions");
                _ValidFileExtensions = StructuralObject.SetValidValue(value, true, "ValidFileExtensions");
                ReportPropertyChanged("ValidFileExtensions");
                OnValidFileExtensionsChanged();
            }
        }
        private global::System.String _ValidFileExtensions;
        partial void OnValidFileExtensionsChanging(global::System.String value);
        partial void OnValidFileExtensionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MinFilesizeInKb
        {
            get
            {
                return _MinFilesizeInKb;
            }
            set
            {
                OnMinFilesizeInKbChanging(value);
                ReportPropertyChanging("MinFilesizeInKb");
                _MinFilesizeInKb = StructuralObject.SetValidValue(value, "MinFilesizeInKb");
                ReportPropertyChanged("MinFilesizeInKb");
                OnMinFilesizeInKbChanged();
            }
        }
        private Nullable<global::System.Int32> _MinFilesizeInKb;
        partial void OnMinFilesizeInKbChanging(Nullable<global::System.Int32> value);
        partial void OnMinFilesizeInKbChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FormBuilderModel", "FK_form_field_values_form_fields", "form_field_values")]
        public EntityCollection<FormFieldValue> FormFieldValues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FormFieldValue>("FormBuilderModel.FK_form_field_values_form_fields", "form_field_values");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FormFieldValue>("FormBuilderModel.FK_form_field_values_form_fields", "form_field_values", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FormBuilderModel", "form_form_fields", "form")]
        public EntityCollection<Form> Forms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Form>("FormBuilderModel.form_form_fields", "form");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Form>("FormBuilderModel.form_form_fields", "form", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FormBuilderModel", Name="FormFieldValue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormFieldValue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FormFieldValue object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fieldId">Initial value of the FieldId property.</param>
        /// <param name="entryId">Initial value of the EntryId property.</param>
        /// <param name="dateAdded">Initial value of the DateAdded property.</param>
        public static FormFieldValue CreateFormFieldValue(global::System.Int32 id, global::System.Int32 fieldId, global::System.Guid entryId, global::System.DateTime dateAdded)
        {
            FormFieldValue formFieldValue = new FormFieldValue();
            formFieldValue.ID = id;
            formFieldValue.FieldId = fieldId;
            formFieldValue.EntryId = entryId;
            formFieldValue.DateAdded = dateAdded;
            return formFieldValue;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FieldId
        {
            get
            {
                return _FieldId;
            }
            set
            {
                OnFieldIdChanging(value);
                ReportPropertyChanging("FieldId");
                _FieldId = StructuralObject.SetValidValue(value, "FieldId");
                ReportPropertyChanged("FieldId");
                OnFieldIdChanged();
            }
        }
        private global::System.Int32 _FieldId;
        partial void OnFieldIdChanging(global::System.Int32 value);
        partial void OnFieldIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid EntryId
        {
            get
            {
                return _EntryId;
            }
            set
            {
                OnEntryIdChanging(value);
                ReportPropertyChanging("EntryId");
                _EntryId = StructuralObject.SetValidValue(value, "EntryId");
                ReportPropertyChanged("EntryId");
                OnEntryIdChanged();
            }
        }
        private global::System.Guid _EntryId;
        partial void OnEntryIdChanging(global::System.Guid value);
        partial void OnEntryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true, "Value");
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value, "DateAdded");
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FormBuilderModel", "FK_form_field_values_form_fields", "form_fields")]
        public FormField FormField
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormField>("FormBuilderModel.FK_form_field_values_form_fields", "form_fields").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormField>("FormBuilderModel.FK_form_field_values_form_fields", "form_fields").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FormField> FormFieldReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormField>("FormBuilderModel.FK_form_field_values_form_fields", "form_fields");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FormField>("FormBuilderModel.FK_form_field_values_form_fields", "form_fields", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
